name: Build and Release

on:
  push:
    tags:
      - 'v*'
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
    steps:
    - uses: actions/checkout@v4

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.21'

    - name: Tidy modules
      run: go mod tidy

    - name: Build
      run: |
        if [ "${{ runner.os }}" == "Linux" ]; then
          GOOS=linux GOARCH=amd64 go build -o fileserver-linux-amd64 fileserver.go
        elif [ "${{ runner.os }}" == "macOS" ]; then
          GOOS=darwin GOARCH=amd64 go build -o fileserver-darwin-amd64 fileserver.go
        else
          GOOS=windows GOARCH=amd64 go build -o fileserver-windows-amd64.exe fileserver.go
        fi

    - name: Upload artifacts
      uses: actions/upload-artifact@v4
      with:
        name: fileserver-${{ matrix.os }}
        path: fileserver-*

  release:
    needs: build
    runs-on: ubuntu-latest
    if: startsWith(github.ref, 'refs/tags/')
    steps:
    - uses: actions/checkout@v4

    - name: Download artifacts
      uses: actions/download-artifact@v4
      with:
        path: artifacts

    - name: Create Release
      uses: softprops/action-gh-release@v1
      with:
        files: |
          artifacts/**/*
        draft: false
        prerelease: false